#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhoCallsFi.Resource", IsApplication=true)]

namespace WhoCallsFi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int about = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btnSimulate = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int btnStart = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnStop = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int editText1 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000e
			public const int AboutDialogOk = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int AboutDialogText = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int AboutDialogTitle = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int DefaultFetchNumber = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int NumberDataFetching = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int ServiceAlreadyStoppedMessage = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int ServiceControlsLabel = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int ServiceIsActive = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ServiceNotActive = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int StartServiceMessage = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int StartServiceText = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int StopServiceText = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int WhoCallsFiServiceName = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
